.TH _BLEND_-common 1 "October 24, 2008" "Debian-_BLEND_"
.SH NAME
.B _BLEND_-common
.B _BLEND_-<metapackage_name>
\- package information and auto-apt helper

.SH SYNOPSIS
.B _BLEND_-common
.B _BLEND_-<metapackage_name>

.SH DESCRIPTION
Print just a simple information page about every _BLEND_-* package
of the Debian _BLEND_ Blend.  Each metapackage has a 
.I /usr/bin/_BLEND_-<metapackage_name>
file which should print some usefull informations and could be serve
as auto-apt helper.

.SH AUTHOR
Andreas Tille <tille@debian.org>.
