#!/bin/bash
#clean up the directories

ls control/* | grep -v "readme" | xargs rm
ls control-sec/* | grep -v "readme" | xargs rm
ls taskdesc/* | grep -v "readme" | xargs rm
ls taskdesc-sec/* | grep -v "readme" | xargs rm