.TH extra-script-which-is-needed-in-task1 1 "<date>" "#BLEND#"
.SH NAME
.B extra-script-which-is-needed-in-task1 
\- some useful script for task1

.SH SYNOPSIS
.B extra-script-which-is-needed-in-task1 

.SH DESCRIPTION
The task makes no sense without this script - or at least this script
provides extra functionality which is not in any of the single
dependencies.

.SH AUTHOR
Metapackage Autor <mpa@debian.org>.
