#!/bin/bash

#parameters: (1)blend_name (2)release_role (3)architecture
#example of usage ./blendsd debian-med testing amd64

psql udd << EOT
SELECT b.blend, b.task, b.package, b.dependency, pkg.architecture
  FROM blends_dependencies b LEFT OUTER JOIN ( 
     SELECT p.package, architecture 
       FROM packages p JOIN releases r ON p.release = r.release 
       WHERE r.role='$2' and architecture='$3' ) pkg ON b.package = pkg.package
  WHERE b.blend='$1'
ORDER BY b.task
EOT
