#!/bin/bash

#arguments: blends
#example of usage ./get_alternatives debian-med

#query to get all the existing alternatives packages from the task files
#this query will ne used to implement my idea, aftewards I will implement Andreas' idea.
#relavant discussion: https://lists.debian.org/debian-blends/2013/07/msg00010.html
psql udd << EOT
SELECT  task, dependency, alternatives, distribution, component
    FROM blends_dependencies_alternatives
  WHERE blend='$1' and alternatives like '%|%'
ORDER BY task
EOT
