#!/bin/bash

#arguments: blends, tasksprefix, release-role
#example of usage ./taskinfo debian-med med testing

#updated blends_tasks table now contains all the info we need and we can get it with a simple query as:
#relevant mail with the update: https://lists.debian.org/debian-blends/2013/06/msg00034.html
psql udd << EOT
SELECT  task, description, section as "Section", enhances as "Enhances", leaf as "Leaf",
	  metapackage, test_always_lang
    FROM blends_tasks 
  WHERE blend='$1'
ORDER BY task
EOT
